/**:
  ros__parameters:
    host_ip: 192.168.1.10
    sensor_ip: 192.168.1.201
    multicast_ip: ""
    data_port: 2368
    gnss_port: 10110
    udp_socket_receive_buffer_size_bytes: 5400000
    packet_mtu_size: 1500
    launch_hw: true
    setup_sensor: true
    udp_only: false
    frame_id: hesai
    diag_span: 1000
    min_range: 0.3
    max_range: 300.0
    cloud_min_angle: 0
    cloud_max_angle: 360
    sync_angle: 0
    cut_angle: 0.0
    sensor_model: PandarQT128
    calibration_file: $(find-pkg-share nebula_decoders)/calibration/hesai/$(var sensor_model).csv
    calibration_download_enabled: true
    rotation_speed: 600
    return_mode: LastStrongest
    ptp_profile: 1588v2
    ptp_domain: 0
    ptp_transport_type: UDP
    ptp_switch_type: TSN
    ptp_lock_threshold: 100
    retry_hw: true
    dual_return_distance_threshold: 0.1
    retro_multi_reflection_filtering: false
    diagnostics:
      pointcloud_publish_rate:
        frequency_ok:
          min_hz: 9.5
          max_hz: 10.5
        frequency_warn:
          min_hz: 9.0
          max_hz: 11.0
      packet_loss:
        error_threshold: 10
