name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble

        include:
          # Humble
          - docker_image: ros:humble
            ros_distribution: humble

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 2 # https://github.com/codecov/codecov-action/issues/190#issuecomment-790729633
      - name: Update image
        run: apt update && rosdep update
        shell: bash
      - name: Prepare Workspace
        run: mkdir -p src && mv `find -maxdepth 1 -not -name . -not -name src` src/
        shell: bash
      - name: Run VCS
        run: cd src && vcs import --force --recursive < build_depends.repos && cd ..
        shell: bash
      - name: Install Dependencies
        run: source /opt/ros/${{ matrix.ros_distribution }}/setup.bash && DEBIAN_FRONTEND=noninteractive rosdep install --include-eol-distros --from-paths src --ignore-src -y -r
        shell: bash
      - name: Build and test
        run: source /opt/ros/${{ matrix.ros_distribution }}/setup.bash &&  colcon build && colcon test --event-handlers console_cohesion+ --packages-skip io_context serial_driver tcp_driver udp_driver
        shell: bash

