name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic

        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy

          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ubuntu:focal
            ros_distribution: galactic

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2 # https://github.com/codecov/codecov-action/issues/190#issuecomment-790729633

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: Run action-ros-ci
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          # Set following option if you need.
          # vcs-repo-file-url: build_depends.repos
          # import-token: ${{ secrets.REPO_TOKEN }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
